# Generated by Django 5.0.7 on 2024-07-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pixabay_id', models.IntegerField(unique=True)),
                ('page_url', models.URLField()),
                ('type', models.CharField(max_length=50)),
                ('tags', models.CharField(max_length=200)),
                ('preview_url', models.URLField()),
                ('webformat_url', models.URLField()),
                ('large_image_url', models.URLField()),
                ('image_width', models.IntegerField()),
                ('image_height', models.IntegerField()),
                ('views', models.IntegerField()),
                ('downloads', models.IntegerField()),
                ('likes', models.IntegerField()),
                ('comments', models.IntegerField()),
                ('user', models.CharField(max_length=100)),
                ('user_image_url', models.URLField()),
            ],
        ),
    ]
